[build]
  base = "."                 # root of project
  publish = "dist"           # Vite build output
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
