# wrangler.toml for Cloudflare Pages + React frontend

# Directory where your built frontend is output
pages_build_output_dir = "../dist"

# Optional environment variables for your frontend build
[env.production]
VITE_BACKEND_URL = "https://qlasar.onrender.com"
