name = "qlasar-frontend"
type = "javascript"
account_id = "41eab5653dbfa595e11425a38f8f76cf"
workers_dev = true
compatibility_date = "2025-10-05"

# Correct output dir
# If your frontend code is in frontend/, Vite outputs to frontend/dist
pages_build_output_dir = "frontend/dist"

[build]
command = "npm --prefix frontend run build"
